"""
Django settings for updater_api project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import datetime
import json
import os
import tomllib
import warnings
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve(strict=True).parent.parent.parent
ENV_FILE = os.path.join(BASE_DIR, ".env")
LOG_DIR = os.path.join(BASE_DIR, "logs")
BUILD_FILE = Path(f"{BASE_DIR}/BUILD.txt")

# .env
if os.path.exists(ENV_FILE):
    load_dotenv(dotenv_path=ENV_FILE, verbose=True)

INSTANCE_NAME = os.getenv("INSTANCE_NAME", "evilflowers.local")

if BUILD_FILE.exists():
    with open(BUILD_FILE) as f:
        BUILD = f.readline().replace("\n", "")
else:
    BUILD = datetime.datetime.now().isoformat()

with open(BASE_DIR / "pyproject.toml", "rb") as f:
    pyproject = tomllib.load(f)
    VERSION = pyproject["tool"]["poetry"]["version"]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(";") + ["localhost"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.postgres",
    "corsheaders",
    "django_api_forms",
    "apps.core",
    "apps.api",
    "apps.files",
    "apps.opds",
    "apps.opds2",
    "apps.openapi",
    "apps.tasks",
    "apps.readium",
    "apps.events",
    "apps.notifications",
    "apps.dataverse",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "apps.api.middleware.exceptions.ExceptionMiddleware",
]

ROOT_URLCONF = "evil_flowers_catalog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "evil_flowers_catalog.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": os.getenv("PGHOST"),
        "PORT": int(os.getenv("PGPORT", 5432)),
        "NAME": os.getenv("PGDATABASE"),
        "USER": os.getenv("PGUSER"),
        "PASSWORD": os.getenv("PGPASSWORD", None),
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]

AUTH_USER_MODEL = "core.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

OBJECT_CHECKERS_MODULE = "apps.core.checkers"

SECURED_VIEW_AUTHENTICATION_SCHEMAS = {
    "Basic": "apps.core.auth.BasicBackend",
    "Bearer": "apps.core.auth.BearerBackend",
}

SECURED_VIEW_JWT_ALGORITHM = "RS256"
SECURED_VIEW_JWK = json.loads(os.getenv("SECURED_VIEW_JWK")) if "SECURED_VIEW_JWK" in os.environ else None
SECURED_VIEW_JWT_ACCESS_TOKEN_EXPIRATION = timedelta(
    minutes=int(os.getenv("SECURED_VIEW_JWT_ACCESS_TOKEN_EXPIRATION", 5))
)
SECURED_VIEW_JWT_REFRESH_TOKEN_EXPIRATION = timedelta(
    minutes=int(os.getenv("SECURED_VIEW_JWT_REFRESH_TOKEN_EXPIRATION", 60 * 24))
)

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

DATETIME_INPUT_FORMATS = ("%Y-%m-%dT%H:%M:%S%z",)

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", os.path.join(BASE_DIR, "media"))

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 100  # 100MB

# Sentry
if os.getenv("SENTRY_DSN", False):

    def before_send(event, hint):
        if "exc_info" in hint:
            exc_type, exc_value, tb = hint["exc_info"]
            if exc_type.__name__ in ["ValidationException", "DisallowedHost"]:
                return None
        if "extra" in event and not event["extra"].get("to_sentry", True):
            return None

        return event

    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            integrations=[DjangoIntegration()],
            attach_stacktrace=True,
            send_default_pii=True,
            before_send=before_send,
            release=VERSION,
        )
    except ImportError:
        warnings.warn("sentry_sdk module is not installed")

# Redis
REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_DATABASE = int(os.getenv("REDIS_DATABASE", "0"))

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DATABASE}",
        "KEY_PREFIX": "evilflowers",
    }
}

# Pagination
EVILFLOWERS_PAGINATION_DEFAULT_LIMIT = int(os.getenv("EVILFLOWERS_PAGINATION_DEFAULT_LIMIT", 10))

# Images & thumbnails
EVILFLOWERS_IMAGE_UPLOAD_MAX_SIZE = int(os.getenv("EVILFLOWERS_IMAGE_UPLOAD_MAX_SIZE", 5)) * 1024 * 1024  # MB
EVILFLOWERS_IMAGE_MIME = (
    "image/gif",
    "image/jpeg",
    "image/png",
)
EVILFLOWERS_IMAGE_THUMBNAIL = (768, 480)

EVILFLOWERS_FEEDS_NEW_LIMIT = os.getenv("EVILFLOWERS_FEEDS_NEW_LIMIT", 20)

EVILFLOWERS_IDENTIFIERS = ["isbn", "google", "doi", "dataverse_pid", "dataverse_dataset_id"]

EVILFLOWERS_ENFORCE_USER_ACQUISITIONS = bool(int(os.getenv("EVILFLOWERS_ENFORCE_USER_ACQUISITIONS", "0")))

EVILFLOWERS_USER_ACQUISITION_MODE = os.getenv("EVILFLOWERS_USER_ACQUISITION_MODE", "single")

# IP blocking: comma-separated CIDR ranges (e.g. "147.175.0.0/16,158.195.0.0/16"), null disables
_ip_ranges = os.getenv("EVILFLOWERS_ALLOWED_IP_RANGES")
EVILFLOWERS_ALLOWED_IP_RANGES = [r.strip() for r in _ip_ranges.split(",") if r.strip()] if _ip_ranges else None

# Storage
EVILFLOWERS_STORAGE_DRIVER = os.getenv("EVILFLOWERS_STORAGE_DRIVER", "apps.files.storage.filesystem.FileSystemStorage")
EVILFLOWERS_STORAGE_FILESYSTEM_DATADIR = os.getenv(
    "EVILFLOWERS_STORAGE_FILESYSTEM_DATADIR", BASE_DIR / "data/evilflowers/storage"
)
EVILFLOWERS_STORAGE_S3_HOST = os.getenv("EVILFLOWERS_STORAGE_S3_HOST")
EVILFLOWERS_STORAGE_S3_ACCESS_KEY = os.getenv("EVILFLOWERS_STORAGE_S3_ACCESS_KEY")
EVILFLOWERS_STORAGE_S3_SECRET_KEY = os.getenv("EVILFLOWERS_STORAGE_S3_SECRET_KEY")
EVILFLOWERS_STORAGE_S3_SECURE = bool(int(os.getenv("EVILFLOWERS_STORAGE_S3_SECURE", 0)))
EVILFLOWERS_STORAGE_S3_BUCKET = os.getenv("EVILFLOWERS_STORAGE_S3_BUCKET")

# Events
EVILFLOWERS_EVENT_BROKER_EXECUTOR = os.getenv("EVILFLOWERS_EVENT_BROKER_EXECUTOR")
EVILFLOWERS_EVENT_BROKER_TRANSFORMER = os.getenv("EVILFLOWERS_EVENT_BROKER_TRANSFORMER")

# Readium
EVILFLOWERS_READIUM_DATADIR = str(os.getenv("EVILFLOWERS_READIUM_DATADIR", BASE_DIR / "data/evilflowers/readium"))
EVILFLOWERS_READIUM_LCPSV_URL = os.getenv("EVILFLOWERS_READIUM_LCPSV_URL", "http://127.0.0.1:8989")
EVILFLOWERS_READIUM_LSDSV_URL = os.getenv("EVILFLOWERS_READIUM_LSDSV_URL", "http://127.0.0.1:8990")
EVILFLOWERS_READIUM_BASE_URL = os.getenv(
    "EVILFLOWERS_READIUM_BASE_URL",
    f"http://{os.getenv('DJANGO_RUNSERVER_IP', '127.0.0.1')}:{os.getenv('DJANGO_RUNSERVER_PORT', '8000')}",
)
EVILFLOWERS_READIUM_DEFAULT_BORROW_DURATION_DAYS = int(
    os.getenv("EVILFLOWERS_READIUM_DEFAULT_BORROW_DURATION_DAYS", 14)
)

# IP-003: renewal policy
EVILFLOWERS_READIUM_MAX_RENEW_DAYS = int(os.getenv("EVILFLOWERS_READIUM_MAX_RENEW_DAYS", 14))
EVILFLOWERS_READIUM_RENEW_EMBARGO_DAYS = int(os.getenv("EVILFLOWERS_READIUM_RENEW_EMBARGO_DAYS", 30))

# IP-003: oversharing detection
EVILFLOWERS_READIUM_OVERSHARE_THRESHOLD = int(os.getenv("EVILFLOWERS_READIUM_OVERSHARE_THRESHOLD", 5))

# IP-003: reservation queue
EVILFLOWERS_READIUM_RESERVATION_CLAIM_HOURS = int(os.getenv("EVILFLOWERS_READIUM_RESERVATION_CLAIM_HOURS", 48))
EVILFLOWERS_READIUM_MAX_RESERVATIONS_PER_USER = int(os.getenv("EVILFLOWERS_READIUM_MAX_RESERVATIONS_PER_USER", 5))

# IP-003: lifecycle notification timing
EVILFLOWERS_READIUM_EXPIRY_REMINDER_DAYS = int(os.getenv("EVILFLOWERS_READIUM_EXPIRY_REMINDER_DAYS", 3))

# IP-009 Phase 5: optional renewal cap. `None` = uncapped (default).
# Set to an integer (e.g. STU policy: 2) to enforce a per-license
# renewal limit in `evaluate_renew`.
_max_renewals = os.getenv("EVILFLOWERS_READIUM_MAX_RENEWALS")
EVILFLOWERS_READIUM_MAX_RENEWALS = int(_max_renewals) if _max_renewals else None

# IP-009 Phase 4: capability-token TTLs (seconds). `LCPL_TTL` covers
# single-use download tokens minted from `POST /licenses/{id}/download-tokens`.
# `LCPL_FEED_TTL` covers multi-use tokens embedded in OPDS feed
# serialization (peek, not consume).
EVILFLOWERS_CAPABILITY_TOKEN_LCPL_TTL_SECONDS = int(os.getenv("EVILFLOWERS_CAPABILITY_TOKEN_LCPL_TTL_SECONDS", 60))
EVILFLOWERS_CAPABILITY_TOKEN_LCPL_FEED_TTL_SECONDS = int(
    os.getenv("EVILFLOWERS_CAPABILITY_TOKEN_LCPL_FEED_TTL_SECONDS", 1800)
)

# OPDS 2.0
EVILFLOWERS_OPDS2_PAGE_SIZE = int(os.getenv("EVILFLOWERS_OPDS2_PAGE_SIZE", 50))
EVILFLOWERS_OPDS2_MAX_PAGE_SIZE = int(os.getenv("EVILFLOWERS_OPDS2_MAX_PAGE_SIZE", 100))

# Search service (IP-008 Phase 6 F1). Consumed by
# `apps/api/services/search_service_client.py::SearchServiceClient`
# and the OPDS 2.0 search view when `?mode=keyword|semantic` is set.
SEARCH_SERVICE_URL = os.getenv("SEARCH_SERVICE_URL", "")
SEARCH_SERVICE_TIMEOUT_SECONDS = int(os.getenv("SEARCH_SERVICE_TIMEOUT_SECONDS", 10))


def _bool_env(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Dataverse integration
# Consumed by apps/dataverse/* (services, views, management commands).
# Operator-facing env names are kept for backwards compatibility, but
# all application code reads these via `django.conf.settings`.
EVILFLOWERS_DATAVERSE_API_TOKEN = (os.getenv("DATAVERSE_API_TOKEN") or "").strip()
EVILFLOWERS_DATAVERSE_WORKFLOW_SECRET = os.getenv("DATAVERSE_WORKFLOW_SECRET", "")
EVILFLOWERS_DATAVERSE_BASE_INTERNAL = (os.getenv("DV_BASE_INTERNAL") or "http://dataverse:8080").rstrip("/")
EVILFLOWERS_DATAVERSE_PUBLIC_BASE = (os.getenv("DV_PUBLIC_BASE") or EVILFLOWERS_DATAVERSE_BASE_INTERNAL).rstrip("/")
# Empty string means "fall back to the dataverse base url at call time".
EVILFLOWERS_DATAVERSE_WORKFLOW_RESUME_BASE = (os.getenv("DV_WORKFLOW_RESUME_BASE") or "").rstrip("/")

# Catalog routing (see apps/dataverse/services/router.py for precedence).
# CATALOG_MAP / GLOBAL_ID_PREFIXES accept JSON strings; the router parses
# them. CATALOG_URL_NAME is the deployment-wide default.
EVILFLOWERS_DATAVERSE_CATALOG_MAP = os.getenv("EVILFLOWERS_DATAVERSE_CATALOG_MAP", "")
EVILFLOWERS_DATAVERSE_GLOBAL_ID_PREFIXES = os.getenv("EVILFLOWERS_DATAVERSE_GLOBAL_ID_PREFIXES", "")
EVILFLOWERS_DATAVERSE_CATALOG_URL_NAME = (os.getenv("DATAVERSE_CATALOG_URL_NAME") or "").strip()

# Sync behaviour
EVILFLOWERS_DATAVERSE_SYNC_DELETE_REMOVED = _bool_env("EVILFLOWERS_DATAVERSE_SYNC_DELETE_REMOVED", default=False)

# Workflow resume (Celery task gating)
EVILFLOWERS_DATAVERSE_RESUME_WORKFLOW = _bool_env("DATAVERSE_RESUME_WORKFLOW", default=False)
EVILFLOWERS_DATAVERSE_RESUME_WORKFLOW_ATTEMPTS = int(os.getenv("DATAVERSE_RESUME_WORKFLOW_ATTEMPTS", 10))
EVILFLOWERS_DATAVERSE_RESUME_WORKFLOW_INITIAL_DELAY = float(os.getenv("DATAVERSE_RESUME_WORKFLOW_INITIAL_DELAY", 1.0))
EVILFLOWERS_DATAVERSE_AUTO_WHITELIST_WORKFLOW_RESUME = _bool_env(
    "DATAVERSE_AUTO_WHITELIST_WORKFLOW_RESUME", default=False
)

# Cache
EVILFLOWERS_CACHE_SERVER_HASHES = timedelta(minutes=int(os.getenv("EVILFLOWERS_CACHE_HASHES", 7 * 24 * 60)))
EVILFLOWERS_CACHE_SERVER_API_KEYS = timedelta(minutes=int(os.getenv("EVILFLOWERS_CACHE_API_KEYS", 0)))
EVILFLOWERS_CACHE_CLIENT_IMAGES = timedelta(minutes=int(os.getenv("EVILFLOWERS_CACHE_CLIENT_IMAGES", 24 * 60)))

# Modifiers
EVILFLOWERS_MODIFIERS = {"application/pdf": "apps.core.modifiers.pdf.PDFModifier"}

# Admin
EVILFLOWERS_CONTACT_EMAIL = os.getenv("CONTACT_EMAIL", "root@localhost")

# Notifications
EVILFLOWERS_NOTIFICATIONS_ENABLED = os.getenv("EVILFLOWERS_NOTIFICATIONS_ENABLED", "false").lower() == "true"
EVILFLOWERS_NOTIFICATION_FROM_EMAIL = os.getenv("EVILFLOWERS_NOTIFICATION_FROM_EMAIL", EVILFLOWERS_CONTACT_EMAIL)
EVILFLOWERS_NOTIFICATION_SCOPED_TOKEN_TTL_HOURS = int(os.getenv("EVILFLOWERS_NOTIFICATION_SCOPED_TOKEN_TTL_HOURS", 72))
EVILFLOWERS_BASE_URL = os.getenv(
    "EVILFLOWERS_BASE_URL",
    f"http://{os.getenv('DJANGO_RUNSERVER_IP', '127.0.0.1')}:{os.getenv('DJANGO_RUNSERVER_PORT', '8000')}",
)

# OpenAPI
EVILFLOWERS_OPENAPI_APPS = ["api", "files", "readium"]

# Backups
EVILFLOWERS_BACKUP_PGDUMP_BIN = os.getenv("EVILFLOWERS_BACKUP_PGDUMP_BIN", "pg_dump")
EVILFLOWERS_BACKUP_SCHEDULE = os.getenv("EVILFLOWERS_BACKUP_SCHEDULE")
EVILFLOWERS_BACKUP_DESTINATION = os.getenv("EVILFLOWERS_BACKUP_DESTINATION")
EVILFLOWERS_BACKUP_S3_HOST = os.environ.get("EVILFLOWERS_BACKUP_S3_HOST")
EVILFLOWERS_BACKUP_S3_ACCESS_KEY = os.environ.get("EVILFLOWERS_BACKUP_S3_ACCESS_KEY")
EVILFLOWERS_BACKUP_S3_SECRET_KEY = os.environ.get("EVILFLOWERS_BACKUP_S3_SECRET_KEY")
EVILFLOWERS_BACKUP_S3_SECURE = os.environ.get("EVILFLOWERS_BACKUP_S3_SECURE", "1").lower() == "1"

DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "%(asctime)s %(levelname)-5s [%(name)s] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
        "syslog": {"class": "logging.handlers.SysLogHandler"},
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "apps": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": DJANGO_LOG_LEVEL,
    },
}

CORS_ALLOW_ALL_ORIGINS = True
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "0") == "1"

if os.getenv("ELASTIC_APM_SERVICE_NAME"):
    INSTALLED_APPS.append("elasticapm.contrib.django")
    LOGGING["handlers"]["elasticapm"] = {
        "level": "INFO",
        "class": "elasticapm.contrib.django.handlers.LoggingHandler",
    }
    LOGGING["root"]["handlers"].append("elasticapm")
    MIDDLEWARE.append("elasticapm.contrib.django.middleware.TracingMiddleware")
    ELASTIC_APM = {
        "DEBUG": True,
    }

# Logfire
# NOTE: instrument_django() is called in apps.core.apps.CoreConfig.ready() because
# calling it here causes a circular import — django.conf.settings is not yet available
# during settings module load, so the OTEL middleware never gets inserted.
if os.getenv("LOGFIRE_TOKEN"):
    try:
        import logfire

        logfire.configure(
            service_name=os.getenv("LOGFIRE_SERVICE_NAME", "evilflowers-catalog"),
            service_version=VERSION,
            environment=os.getenv("LOGFIRE_ENVIRONMENT", "development"),
        )
        logfire.instrument_celery()
        logfire.instrument_requests()
        logfire.instrument_system_metrics()
    except ImportError:
        pass

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DATABASE}")
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE", TIME_ZONE)
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", 30 * 60))  # Default: 30min
CELERY_TASK_ROUTES = {
    "evilflowers_ocr_worker.*": {"queue": "evilflowers_ocr_worker"},
    "evilflowers_lcpencrypt_worker.*": {"queue": "evilflowers_lcpencrypt_worker"},
    "test.*": {"queue": "test"},
}


KAFKA_BROKER_URL = f"{os.getenv('KAFKA_HOST', '127.0.0.1')}:{int(os.getenv('KAFKA_PORT', 9092))}"
