# Generated by Django 5.1 on 2024-08-19 13:56

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobProtocol",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                ("name", models.CharField(max_length=200)),
                ("worker", models.CharField(max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("received", "received"),
                            ("in-progress", "in-progress"),
                            ("failed", "failed"),
                            ("revoked", "revoked"),
                            ("success", "success"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("job_args", models.JSONField(default=list)),
                ("job_kwargs", models.JSONField(default=dict)),
                ("result", models.JSONField(null=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "parent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="tasks.jobprotocol"),
                ),
            ],
            options={
                "verbose_name": "Job protocol",
                "verbose_name_plural": "Job protocols",
                "db_table": "job_protocols",
                "default_permissions": ("view", "add"),
            },
        ),
    ]
