services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=evil_flowers_catalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: .
    volumes:
      - ./media:/usr/local/app/media
      - ./private:/usr/local/app/private
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=evil_flowers_catalog
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=evil_flowers_catalog.settings.development
    ports:
      - 8000:8000
    depends_on:
      - db
