--
-- PostgreSQL database dump
--

\restrict 4TwpdLmKMEfGw42DsT0OLmGKBCzh2JVpDcmwie0DtJ8TsqUXPIHTPNRGNQKiXlP

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: hstore; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;


--
-- Name: EXTENSION hstore; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION hstore IS 'data type for storing sets of (key, value) pairs';


--
-- Name: unaccent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;


--
-- Name: EXTENSION unaccent; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION unaccent IS 'text search dictionary that removes accents';


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: acquisitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.acquisitions (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    relation character varying(20) NOT NULL,
    mime character varying(100) NOT NULL,
    content character varying(255),
    entry_id uuid NOT NULL,
    file_url character varying(2048)
);


--
-- Name: annotation_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annotation_items (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    page smallint NOT NULL,
    content text NOT NULL,
    annotation_id uuid NOT NULL,
    CONSTRAINT annotation_items_page_check CHECK ((page >= 0))
);


--
-- Name: annotations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annotations (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    user_acquisition_id uuid NOT NULL,
    title character varying(255) NOT NULL
);


--
-- Name: api_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_keys (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    name character varying(200),
    is_active boolean NOT NULL,
    user_id uuid NOT NULL,
    last_seen_at timestamp with time zone
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_sources (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    name character varying(200) NOT NULL,
    driver character varying(20) NOT NULL,
    content jsonb,
    is_active boolean NOT NULL
);


--
-- Name: authors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authors (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    name character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    catalog_id uuid NOT NULL
);


--
-- Name: catalogs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.catalogs (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    url_name character varying(50) NOT NULL,
    title character varying(100) NOT NULL,
    creator_id uuid NOT NULL,
    is_public boolean NOT NULL,
    touched_at timestamp with time zone
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    term character varying(255) NOT NULL,
    label character varying(255),
    scheme character varying(255),
    catalog_id uuid NOT NULL,
    creator_id uuid NOT NULL
);


--
-- Name: currencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.currencies (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(3) NOT NULL
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: encrypted_contents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.encrypted_contents (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    status character varying(20) NOT NULL,
    lcp_content_id character varying(255) NOT NULL,
    encrypted_path character varying(500) NOT NULL,
    encrypted_url character varying(500),
    encryption_algorithm character varying(50) NOT NULL,
    content_key_encrypted text,
    encrypted_at timestamp with time zone,
    registered_at timestamp with time zone,
    error_message text,
    acquisition_id uuid NOT NULL
);


--
-- Name: entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entries (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    title character varying(255) NOT NULL,
    summary text,
    content text,
    catalog_id uuid NOT NULL,
    creator_id uuid NOT NULL,
    language_id uuid,
    image character varying(255),
    image_mime character varying(100),
    thumbnail character varying(255),
    popularity bigint NOT NULL,
    identifiers public.hstore,
    citation text,
    config jsonb NOT NULL,
    published_at timestamp with time zone,
    publisher character varying(255),
    touched_at timestamp with time zone,
    CONSTRAINT entries_popularity_check CHECK ((popularity >= 0))
);


--
-- Name: entry_authors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entry_authors (
    id integer NOT NULL,
    "position" smallint NOT NULL,
    author_id uuid NOT NULL,
    entry_id uuid NOT NULL,
    CONSTRAINT entry_authors_position_check CHECK (("position" >= 0))
);


--
-- Name: entry_authors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.entry_authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entry_authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entry_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entry_categories (
    id integer NOT NULL,
    entry_id uuid NOT NULL,
    category_id uuid NOT NULL
);


--
-- Name: entry_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.entry_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entry_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feed_parents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feed_parents (
    id integer NOT NULL,
    from_feed_id uuid NOT NULL,
    to_feed_id uuid NOT NULL
);


--
-- Name: feed_parents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feed_parents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feed_parents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feeds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feeds (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    title character varying(100) NOT NULL,
    url_name character varying(50) NOT NULL,
    kind character varying(20) NOT NULL,
    source character varying(20) NOT NULL,
    content text NOT NULL,
    per_page integer,
    catalog_id uuid NOT NULL,
    creator_id uuid NOT NULL,
    touched_at timestamp with time zone
);


--
-- Name: feeds_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feeds_entries (
    id integer NOT NULL,
    feed_id uuid NOT NULL,
    entry_id uuid NOT NULL
);


--
-- Name: feeds_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feeds_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feeds_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_protocols; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_protocols (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    name character varying(200) NOT NULL,
    worker character varying(50),
    status character varying(20) NOT NULL,
    job_args jsonb NOT NULL,
    job_kwargs jsonb NOT NULL,
    result jsonb,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    parent_id uuid
);


--
-- Name: languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.languages (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    name character varying(100) NOT NULL,
    alpha2 character varying(2) NOT NULL,
    alpha3 character varying(3)
);


--
-- Name: licenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.licenses (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    state character varying(15) NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    entry_id uuid NOT NULL,
    user_id uuid NOT NULL,
    device_count integer NOT NULL,
    lcp_license_id uuid,
    passphrase_hash character varying(64),
    passphrase_hint character varying(255),
    encrypted_content_id uuid,
    CONSTRAINT licenses_device_count_check CHECK ((device_count >= 0))
);


--
-- Name: prices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prices (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    value numeric(12,4) NOT NULL,
    acquisition_id uuid NOT NULL,
    currency_id uuid NOT NULL
);


--
-- Name: shelf_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shelf_records (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    entry_id uuid NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: user_acquisitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_acquisitions (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    type character varying(10) NOT NULL,
    range character varying(100),
    expire_at timestamp with time zone,
    acquisition_id uuid NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: user_catalogs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_catalogs (
    id integer NOT NULL,
    mode character varying(10) NOT NULL,
    catalog_id uuid NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: user_catalogs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_catalogs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_catalogs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    username character varying(200) NOT NULL,
    name character varying(30) NOT NULL,
    surname character varying(150) NOT NULL,
    is_active boolean NOT NULL,
    auth_source_id uuid NOT NULL
);


--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_groups (
    id integer NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_permissions (
    id integer NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: acquisitions acquisitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisitions
    ADD CONSTRAINT acquisitions_pkey PRIMARY KEY (id);


--
-- Name: annotation_items annotation_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_items
    ADD CONSTRAINT annotation_items_pkey PRIMARY KEY (id);


--
-- Name: annotations annotations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT annotations_pkey PRIMARY KEY (id);


--
-- Name: api_keys api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_sources auth_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sources
    ADD CONSTRAINT auth_sources_pkey PRIMARY KEY (id);


--
-- Name: authors authors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);


--
-- Name: catalogs catalogs_creator_id_title_c18ccc47_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalogs
    ADD CONSTRAINT catalogs_creator_id_title_c18ccc47_uniq UNIQUE (creator_id, title);


--
-- Name: catalogs catalogs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalogs
    ADD CONSTRAINT catalogs_pkey PRIMARY KEY (id);


--
-- Name: catalogs catalogs_url_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalogs
    ADD CONSTRAINT catalogs_url_name_key UNIQUE (url_name);


--
-- Name: categories categories_catalog_id_term_ac2a446b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_catalog_id_term_ac2a446b_uniq UNIQUE (catalog_id, term);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: currencies currencies_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_code_key UNIQUE (code);


--
-- Name: currencies currencies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: encrypted_contents encrypted_contents_acquisition_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.encrypted_contents
    ADD CONSTRAINT encrypted_contents_acquisition_id_key UNIQUE (acquisition_id);


--
-- Name: encrypted_contents encrypted_contents_lcp_content_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.encrypted_contents
    ADD CONSTRAINT encrypted_contents_lcp_content_id_key UNIQUE (lcp_content_id);


--
-- Name: encrypted_contents encrypted_contents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.encrypted_contents
    ADD CONSTRAINT encrypted_contents_pkey PRIMARY KEY (id);


--
-- Name: entries entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entries
    ADD CONSTRAINT entries_pkey PRIMARY KEY (id);


--
-- Name: entry_authors entry_authors_entry_id_author_id_885e267a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entry_authors
    ADD CONSTRAINT entry_authors_entry_id_author_id_885e267a_uniq UNIQUE (entry_id, author_id);


--
-- Name: entry_authors entry_authors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entry_authors
    ADD CONSTRAINT entry_authors_pkey PRIMARY KEY (id);


--
-- Name: entry_categories entry_categories_entry_id_category_id_2192e3fe_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entry_categories
    ADD CONSTRAINT entry_categories_entry_id_category_id_2192e3fe_uniq UNIQUE (entry_id, category_id);


--
-- Name: entry_categories entry_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entry_categories
    ADD CONSTRAINT entry_categories_pkey PRIMARY KEY (id);


--
-- Name: feed_parents feed_parents_from_feed_id_to_feed_id_b9e2f43d_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feed_parents
    ADD CONSTRAINT feed_parents_from_feed_id_to_feed_id_b9e2f43d_uniq UNIQUE (from_feed_id, to_feed_id);


--
-- Name: feed_parents feed_parents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feed_parents
    ADD CONSTRAINT feed_parents_pkey PRIMARY KEY (id);


--
-- Name: feeds feeds_catalog_id_title_8a52beb7_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT feeds_catalog_id_title_8a52beb7_uniq UNIQUE (catalog_id, title);


--
-- Name: feeds feeds_catalog_id_url_name_971610a5_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT feeds_catalog_id_url_name_971610a5_uniq UNIQUE (catalog_id, url_name);


--
-- Name: feeds_entries feeds_entries_feed_id_entry_id_4d7d2bc5_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feeds_entries
    ADD CONSTRAINT feeds_entries_feed_id_entry_id_4d7d2bc5_uniq UNIQUE (feed_id, entry_id);


--
-- Name: feeds_entries feeds_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feeds_entries
    ADD CONSTRAINT feeds_entries_pkey PRIMARY KEY (id);


--
-- Name: feeds feeds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT feeds_pkey PRIMARY KEY (id);


--
-- Name: job_protocols job_protocols_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_protocols
    ADD CONSTRAINT job_protocols_pkey PRIMARY KEY (id);


--
-- Name: languages languages_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT languages_code_key UNIQUE (alpha2);


--
-- Name: languages languages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT languages_pkey PRIMARY KEY (id);


--
-- Name: licenses licenses_entry_id_user_id_state_cb17be2a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.licenses
    ADD CONSTRAINT licenses_entry_id_user_id_state_cb17be2a_uniq UNIQUE (entry_id, user_id, state);


--
-- Name: licenses licenses_lcp_license_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.licenses
    ADD CONSTRAINT licenses_lcp_license_id_key UNIQUE (lcp_license_id);


--
-- Name: licenses licenses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.licenses
    ADD CONSTRAINT licenses_pkey PRIMARY KEY (id);


--
-- Name: prices prices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prices
    ADD CONSTRAINT prices_pkey PRIMARY KEY (id);


--
-- Name: shelf_records shelf_records_entry_id_user_id_9cb61b49_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shelf_records
    ADD CONSTRAINT shelf_records_entry_id_user_id_9cb61b49_uniq UNIQUE (entry_id, user_id);


--
-- Name: shelf_records shelf_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shelf_records
    ADD CONSTRAINT shelf_records_pkey PRIMARY KEY (id);


--
-- Name: user_acquisitions user_acquisitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_acquisitions
    ADD CONSTRAINT user_acquisitions_pkey PRIMARY KEY (id);


--
-- Name: user_catalogs user_catalogs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_catalogs
    ADD CONSTRAINT user_catalogs_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (username);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: acquisitions_entry_id_b0616ca5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX acquisitions_entry_id_b0616ca5 ON public.acquisitions USING btree (entry_id);


--
-- Name: annotation_items_annotation_id_5b286be6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotation_items_annotation_id_5b286be6 ON public.annotation_items USING btree (annotation_id);


--
-- Name: annotations_user_acquisition_id_2602cfc7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annotations_user_acquisition_id_2602cfc7 ON public.annotations USING btree (user_acquisition_id);


--
-- Name: api_keys_user_id_1367826c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_keys_user_id_1367826c ON public.api_keys USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authors_catalog_1879b0_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authors_catalog_1879b0_idx ON public.authors USING btree (catalog_id, name);


--
-- Name: authors_catalog_430ad2_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authors_catalog_430ad2_idx ON public.authors USING btree (catalog_id, name, surname);


--
-- Name: authors_catalog_dd6286_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authors_catalog_dd6286_idx ON public.authors USING btree (catalog_id, surname);


--
-- Name: authors_catalog_ec9507_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authors_catalog_ec9507_idx ON public.authors USING btree (catalog_id);


--
-- Name: authors_catalog_id_8dd8655d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authors_catalog_id_8dd8655d ON public.authors USING btree (catalog_id);


--
-- Name: authors_name_e12c66_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authors_name_e12c66_idx ON public.authors USING btree (name);


--
-- Name: authors_surname_8ee6cb_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authors_surname_8ee6cb_idx ON public.authors USING btree (surname);


--
-- Name: catalogs_creator_4ca17b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX catalogs_creator_4ca17b_idx ON public.catalogs USING btree (creator_id, is_public);


--
-- Name: catalogs_creator_c9ef49_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX catalogs_creator_c9ef49_idx ON public.catalogs USING btree (creator_id);


--
-- Name: catalogs_creator_id_11624af6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX catalogs_creator_id_11624af6 ON public.catalogs USING btree (creator_id);


--
-- Name: catalogs_is_publ_82fb10_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX catalogs_is_publ_82fb10_idx ON public.catalogs USING btree (is_public);


--
-- Name: catalogs_is_publ_ad1013_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX catalogs_is_publ_ad1013_idx ON public.catalogs USING btree (is_public, title);


--
-- Name: catalogs_title_9825a7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX catalogs_title_9825a7_idx ON public.catalogs USING btree (title);


--
-- Name: catalogs_touched_4b4131_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX catalogs_touched_4b4131_idx ON public.catalogs USING btree (touched_at);


--
-- Name: catalogs_url_nam_64ae26_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX catalogs_url_nam_64ae26_idx ON public.catalogs USING btree (url_name);


--
-- Name: catalogs_url_name_fcbf85f1_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX catalogs_url_name_fcbf85f1_like ON public.catalogs USING btree (url_name varchar_pattern_ops);


--
-- Name: categories_catalog_0f30ce_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX categories_catalog_0f30ce_idx ON public.categories USING btree (catalog_id, label);


--
-- Name: categories_catalog_82b239_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX categories_catalog_82b239_idx ON public.categories USING btree (catalog_id);


--
-- Name: categories_catalog_eac6e3_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX categories_catalog_eac6e3_idx ON public.categories USING btree (catalog_id, term);


--
-- Name: categories_catalog_id_5bc5f1a1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX categories_catalog_id_5bc5f1a1 ON public.categories USING btree (catalog_id);


--
-- Name: categories_creator_id_f54be628; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX categories_creator_id_f54be628 ON public.categories USING btree (creator_id);


--
-- Name: categories_label_4454dd_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX categories_label_4454dd_idx ON public.categories USING btree (label);


--
-- Name: categories_scheme_90c0e3_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX categories_scheme_90c0e3_idx ON public.categories USING btree (scheme);


--
-- Name: categories_term_6c009e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX categories_term_6c009e_idx ON public.categories USING btree (term);


--
-- Name: currencies_code_169576e8_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX currencies_code_169576e8_like ON public.currencies USING btree (code varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: encrypted_contents_lcp_content_id_3f41c141_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX encrypted_contents_lcp_content_id_3f41c141_like ON public.encrypted_contents USING btree (lcp_content_id varchar_pattern_ops);


--
-- Name: entries_catalog_196e6c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_catalog_196e6c_idx ON public.entries USING btree (catalog_id, language_id);


--
-- Name: entries_catalog_3691fa_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_catalog_3691fa_idx ON public.entries USING btree (catalog_id, published_at);


--
-- Name: entries_catalog_42380f_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_catalog_42380f_idx ON public.entries USING btree (catalog_id, popularity DESC);


--
-- Name: entries_catalog_694470_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_catalog_694470_idx ON public.entries USING btree (catalog_id, created_at DESC, popularity DESC);


--
-- Name: entries_catalog_91739a_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_catalog_91739a_idx ON public.entries USING btree (catalog_id, published_at, popularity DESC);


--
-- Name: entries_catalog_d19708_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_catalog_d19708_idx ON public.entries USING btree (catalog_id, language_id, popularity DESC);


--
-- Name: entries_catalog_e9d460_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_catalog_e9d460_idx ON public.entries USING btree (catalog_id, created_at DESC);


--
-- Name: entries_catalog_id_048223e3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_catalog_id_048223e3 ON public.entries USING btree (catalog_id);


--
-- Name: entries_creator_ad48e1_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_creator_ad48e1_idx ON public.entries USING btree (creator_id);


--
-- Name: entries_creator_id_96a09c71; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_creator_id_96a09c71 ON public.entries USING btree (creator_id);


--
-- Name: entries_language_id_fe4c7274; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_language_id_fe4c7274 ON public.entries USING btree (language_id);


--
-- Name: entries_publish_a5e2a1_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_publish_a5e2a1_idx ON public.entries USING btree (publisher);


--
-- Name: entries_summary_2be75a_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_summary_2be75a_idx ON public.entries USING btree (summary, catalog_id);


--
-- Name: entries_title_0ad36c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_title_0ad36c_idx ON public.entries USING btree (title);


--
-- Name: entries_title_c498b5_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_title_c498b5_idx ON public.entries USING btree (title, catalog_id);


--
-- Name: entry_authors_author_id_a653a28e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entry_authors_author_id_a653a28e ON public.entry_authors USING btree (author_id);


--
-- Name: entry_authors_entry_id_bb4d9d27; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entry_authors_entry_id_bb4d9d27 ON public.entry_authors USING btree (entry_id);


--
-- Name: entry_categories_category_id_7184cacc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entry_categories_category_id_7184cacc ON public.entry_categories USING btree (category_id);


--
-- Name: entry_categories_entry_id_73313968; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entry_categories_entry_id_73313968 ON public.entry_categories USING btree (entry_id);


--
-- Name: feed_parents_from_feed_id_51298c5c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX feed_parents_from_feed_id_51298c5c ON public.feed_parents USING btree (from_feed_id);


--
-- Name: feed_parents_to_feed_id_227e4409; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX feed_parents_to_feed_id_227e4409 ON public.feed_parents USING btree (to_feed_id);


--
-- Name: feeds_catalog_id_58842949; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX feeds_catalog_id_58842949 ON public.feeds USING btree (catalog_id);


--
-- Name: feeds_creator_id_5fae2a18; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX feeds_creator_id_5fae2a18 ON public.feeds USING btree (creator_id);


--
-- Name: feeds_entries_entry_id_1c6d78c1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX feeds_entries_entry_id_1c6d78c1 ON public.feeds_entries USING btree (entry_id);


--
-- Name: feeds_entries_feed_id_d6a4b674; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX feeds_entries_feed_id_d6a4b674 ON public.feeds_entries USING btree (feed_id);


--
-- Name: feeds_url_name_9f23419d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX feeds_url_name_9f23419d ON public.feeds USING btree (url_name);


--
-- Name: feeds_url_name_9f23419d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX feeds_url_name_9f23419d_like ON public.feeds USING btree (url_name varchar_pattern_ops);


--
-- Name: job_protocols_parent_id_df73cbe0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX job_protocols_parent_id_df73cbe0 ON public.job_protocols USING btree (parent_id);


--
-- Name: languages_code_cb780636_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX languages_code_cb780636_like ON public.languages USING btree (alpha2 varchar_pattern_ops);


--
-- Name: licenses_encrypted_content_id_33c1f6af; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX licenses_encrypted_content_id_33c1f6af ON public.licenses USING btree (encrypted_content_id);


--
-- Name: licenses_entry_id_29d7dcd3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX licenses_entry_id_29d7dcd3 ON public.licenses USING btree (entry_id);


--
-- Name: licenses_user_id_d09899c7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX licenses_user_id_d09899c7 ON public.licenses USING btree (user_id);


--
-- Name: prices_acquisition_id_f15203c1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX prices_acquisition_id_f15203c1 ON public.prices USING btree (acquisition_id);


--
-- Name: prices_currency_id_1711c0af; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX prices_currency_id_1711c0af ON public.prices USING btree (currency_id);


--
-- Name: shelf_records_entry_id_8de6a98a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shelf_records_entry_id_8de6a98a ON public.shelf_records USING btree (entry_id);


--
-- Name: shelf_records_user_id_d226795c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shelf_records_user_id_d226795c ON public.shelf_records USING btree (user_id);


--
-- Name: user_acquisitions_acquisition_id_ef574b40; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_acquisitions_acquisition_id_ef574b40 ON public.user_acquisitions USING btree (acquisition_id);


--
-- Name: user_acquisitions_user_id_344aae83; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_acquisitions_user_id_344aae83 ON public.user_acquisitions USING btree (user_id);


--
-- Name: user_catalogs_catalog_id_94dc40b1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_catalogs_catalog_id_94dc40b1 ON public.user_catalogs USING btree (catalog_id);


--
-- Name: user_catalogs_user_id_5a96dc94; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_catalogs_user_id_5a96dc94 ON public.user_catalogs USING btree (user_id);


--
-- Name: users_auth_source_id_b53aa4af; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_auth_source_id_b53aa4af ON public.users USING btree (auth_source_id);


--
-- Name: users_email_0ea73cca_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_email_0ea73cca_like ON public.users USING btree (username varchar_pattern_ops);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: acquisitions acquisitions_entry_id_b0616ca5_fk_entries_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisitions
    ADD CONSTRAINT acquisitions_entry_id_b0616ca5_fk_entries_id FOREIGN KEY (entry_id) REFERENCES public.entries(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotation_items annotation_items_annotation_id_5b286be6_fk_annotations_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotation_items
    ADD CONSTRAINT annotation_items_annotation_id_5b286be6_fk_annotations_id FOREIGN KEY (annotation_id) REFERENCES public.annotations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: annotations annotations_user_acquisition_id_2602cfc7_fk_user_acqu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT annotations_user_acquisition_id_2602cfc7_fk_user_acqu FOREIGN KEY (user_acquisition_id) REFERENCES public.user_acquisitions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_keys api_keys_user_id_1367826c_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_user_id_1367826c_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authors authors_catalog_id_8dd8655d_fk_catalogs_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_catalog_id_8dd8655d_fk_catalogs_id FOREIGN KEY (catalog_id) REFERENCES public.catalogs(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalogs catalogs_creator_id_11624af6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalogs
    ADD CONSTRAINT catalogs_creator_id_11624af6_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: categories categories_catalog_id_5bc5f1a1_fk_catalogs_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_catalog_id_5bc5f1a1_fk_catalogs_id FOREIGN KEY (catalog_id) REFERENCES public.catalogs(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: categories categories_creator_id_f54be628_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_creator_id_f54be628_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: encrypted_contents encrypted_contents_acquisition_id_9333a02d_fk_acquisitions_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.encrypted_contents
    ADD CONSTRAINT encrypted_contents_acquisition_id_9333a02d_fk_acquisitions_id FOREIGN KEY (acquisition_id) REFERENCES public.acquisitions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entries entries_catalog_id_048223e3_fk_catalogs_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entries
    ADD CONSTRAINT entries_catalog_id_048223e3_fk_catalogs_id FOREIGN KEY (catalog_id) REFERENCES public.catalogs(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entries entries_creator_id_96a09c71_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entries
    ADD CONSTRAINT entries_creator_id_96a09c71_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entries entries_language_id_fe4c7274_fk_languages_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entries
    ADD CONSTRAINT entries_language_id_fe4c7274_fk_languages_id FOREIGN KEY (language_id) REFERENCES public.languages(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entry_authors entry_authors_author_id_a653a28e_fk_authors_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entry_authors
    ADD CONSTRAINT entry_authors_author_id_a653a28e_fk_authors_id FOREIGN KEY (author_id) REFERENCES public.authors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entry_authors entry_authors_entry_id_bb4d9d27_fk_entries_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entry_authors
    ADD CONSTRAINT entry_authors_entry_id_bb4d9d27_fk_entries_id FOREIGN KEY (entry_id) REFERENCES public.entries(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entry_categories entry_categories_category_id_7184cacc_fk_categories_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entry_categories
    ADD CONSTRAINT entry_categories_category_id_7184cacc_fk_categories_id FOREIGN KEY (category_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entry_categories entry_categories_entry_id_73313968_fk_entries_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entry_categories
    ADD CONSTRAINT entry_categories_entry_id_73313968_fk_entries_id FOREIGN KEY (entry_id) REFERENCES public.entries(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: feed_parents feed_parents_from_feed_id_51298c5c_fk_feeds_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feed_parents
    ADD CONSTRAINT feed_parents_from_feed_id_51298c5c_fk_feeds_id FOREIGN KEY (from_feed_id) REFERENCES public.feeds(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: feed_parents feed_parents_to_feed_id_227e4409_fk_feeds_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feed_parents
    ADD CONSTRAINT feed_parents_to_feed_id_227e4409_fk_feeds_id FOREIGN KEY (to_feed_id) REFERENCES public.feeds(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: feeds feeds_catalog_id_58842949_fk_catalogs_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT feeds_catalog_id_58842949_fk_catalogs_id FOREIGN KEY (catalog_id) REFERENCES public.catalogs(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: feeds feeds_creator_id_5fae2a18_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT feeds_creator_id_5fae2a18_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: feeds_entries feeds_entries_entry_id_1c6d78c1_fk_entries_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feeds_entries
    ADD CONSTRAINT feeds_entries_entry_id_1c6d78c1_fk_entries_id FOREIGN KEY (entry_id) REFERENCES public.entries(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: feeds_entries feeds_entries_feed_id_d6a4b674_fk_feeds_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feeds_entries
    ADD CONSTRAINT feeds_entries_feed_id_d6a4b674_fk_feeds_id FOREIGN KEY (feed_id) REFERENCES public.feeds(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: job_protocols job_protocols_parent_id_df73cbe0_fk_job_protocols_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_protocols
    ADD CONSTRAINT job_protocols_parent_id_df73cbe0_fk_job_protocols_id FOREIGN KEY (parent_id) REFERENCES public.job_protocols(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: licenses licenses_encrypted_content_id_33c1f6af_fk_encrypted_contents_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.licenses
    ADD CONSTRAINT licenses_encrypted_content_id_33c1f6af_fk_encrypted_contents_id FOREIGN KEY (encrypted_content_id) REFERENCES public.encrypted_contents(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: licenses licenses_entry_id_29d7dcd3_fk_entries_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.licenses
    ADD CONSTRAINT licenses_entry_id_29d7dcd3_fk_entries_id FOREIGN KEY (entry_id) REFERENCES public.entries(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: licenses licenses_user_id_d09899c7_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.licenses
    ADD CONSTRAINT licenses_user_id_d09899c7_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prices prices_acquisition_id_f15203c1_fk_acquisitions_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prices
    ADD CONSTRAINT prices_acquisition_id_f15203c1_fk_acquisitions_id FOREIGN KEY (acquisition_id) REFERENCES public.acquisitions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prices prices_currency_id_1711c0af_fk_currencies_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prices
    ADD CONSTRAINT prices_currency_id_1711c0af_fk_currencies_id FOREIGN KEY (currency_id) REFERENCES public.currencies(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shelf_records shelf_records_entry_id_8de6a98a_fk_entries_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shelf_records
    ADD CONSTRAINT shelf_records_entry_id_8de6a98a_fk_entries_id FOREIGN KEY (entry_id) REFERENCES public.entries(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shelf_records shelf_records_user_id_d226795c_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shelf_records
    ADD CONSTRAINT shelf_records_user_id_d226795c_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_acquisitions user_acquisitions_acquisition_id_ef574b40_fk_acquisitions_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_acquisitions
    ADD CONSTRAINT user_acquisitions_acquisition_id_ef574b40_fk_acquisitions_id FOREIGN KEY (acquisition_id) REFERENCES public.acquisitions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_acquisitions user_acquisitions_user_id_344aae83_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_acquisitions
    ADD CONSTRAINT user_acquisitions_user_id_344aae83_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_catalogs user_catalogs_catalog_id_94dc40b1_fk_catalogs_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_catalogs
    ADD CONSTRAINT user_catalogs_catalog_id_94dc40b1_fk_catalogs_id FOREIGN KEY (catalog_id) REFERENCES public.catalogs(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_catalogs user_catalogs_user_id_5a96dc94_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_catalogs
    ADD CONSTRAINT user_catalogs_user_id_5a96dc94_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_auth_source_id_b53aa4af_fk_auth_sources_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_auth_source_id_b53aa4af_fk_auth_sources_id FOREIGN KEY (auth_source_id) REFERENCES public.auth_sources(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 4TwpdLmKMEfGw42DsT0OLmGKBCzh2JVpDcmwie0DtJ8TsqUXPIHTPNRGNQKiXlP

