[tool.poetry]
name = "evil_flowers_catalog"
version = "0.5.0"
description = "Simple books catalog compatible with OPDS written in Python"
authors = ["Jakub Dubec <jakub.dubec@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.0.0"
django_api_forms = "1.0.0rc2"
python-dotenv = "^0.20.0"
argon2-cffi = "^21.3.0"
sentry-sdk = "^1.5"
psycopg2 = "^2.9"
porcupine-python = "^0"
django-imap-backend = "^0"
django-filter = "^21.1"
redis = "^4.3"
Pillow = "^9.1"
python-crontab = "^2.6.0"
pycountry = "^22.3"
django-object-checker = "^1.0.0"
Authlib = "^1"
tzdata = "^2022.1"
django-cors-headers = "^3.13.0"
python-ldap = "^3.4.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
