[tool.poetry]
name = "evil_flowers_catalog"
version = "0.5.0"
description = "Simple books catalog compatible with OPDS written in Python"
authors = ["Jakub Dubec <jakub.dubec@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.0"
django_api_forms = "1.0.0rc9"
python-dotenv = "^1.0"
argon2-cffi = "^21.3.0"
sentry-sdk = "^1.19"
psycopg = {version = "^3.1", extras = ["c"]}
porcupine-python = "^0"
django-imap-backend = "^0"
django-filter = "^23.2"
redis = "^4.5"
Pillow = "^9.5"
python-crontab = "^2.7"
pycountry = "^22.3"
django-object-checker = "^1.0.0"
Authlib = "^1.2"
tzdata = "^2023.3"
django-cors-headers = "^3.14"
python-ldap = "^3.4.0"
pypdf = { version = "^3.7", optional = true }
fpdf2 = { version = "^2.7", optional = true }
minio = { version = "^7.1.12", optional = true }
qrcode = "^7.4"
bibtexparser = "^1.4.0"
isbnlib = "^3.10.14"

[tool.poetry.dev-dependencies]
flake8 = "^6.0"

[tool.poetry.extras]
s3 = ["minio"]
pdf = ["pypdf", "fpdf2"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.masonry.api"
