[tool.poetry]
name = "evil_flowers_catalog"
version = "0.5.0"
description = "Simple books catalog compatible with OPDS written in Python"
authors = ["Jakub Dubec <jakub.dubec@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.0.0"
django_api_forms = "^0"
python-dotenv = "^0.19.0"
argon2-cffi = "^21.0.0"
sentry-sdk = "^1.5"
psycopg2 = "^2.8.6"
porcupine-python = "^0"
django-imap-backend = "^0"
django-filter = "^21.0"
redis = "^4.0"
Pillow = "^9.0"
python-crontab = "^2.5.1"
pycountry = "^22.0"
django-object-checker = "^1.0.0"
Authlib = "^0.15.5"
tzdata = "^2021.5"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
