[tool.poetry]
name = "evil_flowers_catalog"
version = "0.3.0"
description = "Simple books catalog compatible with OPDS written in Python"
authors = ["Jakub Dubec <jakub.dubec@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
django = "^3.2.1"
django_api_forms = "^0"
python-dotenv = "^0.14.0"
argon2-cffi = "^20.1.0"
sentry-sdk = "^1.0"
psycopg2 = "^2.8.6"
porcupine-python = "^0"
django-imap-backend = "^0"
requests = "^2.24.0"
django-filter = "^2.4.0"
django-celery-beat = "^2.2.0"
redis = "^3.5.3"
idna = "2.10"

[tool.poetry.dev-dependencies]
fabric = "^2.5.0"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
