# Generated by Django 3.2.6 on 2021-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_api_keys"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contributor",
        ),
        migrations.AddField(
            model_name="entry",
            name="contributors",
            field=models.ManyToManyField(
                db_table="contributors",
                related_name="contribution_entries",
                to="core.Author",
                verbose_name="Contributor",
            ),
        ),
    ]
