# Generated by Django 3.2.6 on 2021-08-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_contributors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feed",
            options={
                "default_permissions": (),
                "verbose_name": "Feed",
                "verbose_name_plural": "Feeds",
            },
        ),
        migrations.RemoveField(
            model_name="feed",
            name="parent",
        ),
        migrations.AddField(
            model_name="feed",
            name="parents",
            field=models.ManyToManyField(
                db_table="feed_parents", related_name="children", to="core.Feed"
            ),
        ),
    ]
