# Generated by Django 4.0.2 on 2022-02-12 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_legacy_user_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='users',
            field=models.ManyToManyField(related_name='catalogs', through='core.UserCatalog', to=settings.AUTH_USER_MODEL),
        ),
    ]
