# Generated by Django 4.2.1 on 2023-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_entry_config_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="citation",
            field=models.TextField(null=True),
        ),
    ]
