# Generated by Django 4.2.1 on 2023-05-08 09:00

import apps.core.validators
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_entry_citation_as_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='identifiers',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True, validators=[apps.core.validators.AvailableKeysValidator(keys=['isbn', 'google', 'doi'])]),
        ),
    ]
