# Generated by Django 4.2.6 on 2023-10-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_shelfrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('catalog', 'url_name'), ('catalog', 'title')},
        ),
    ]
