# Generated by Django 5.0.1 on 2024-01-14 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_database_timestamps"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("catalog", "term")},
        ),
    ]
