# Generated by Django 5.0.1 on 2024-01-18 21:14

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    AnnotationItem = apps.get_model("core", "AnnotationItem")
    Annotation = apps.get_model("core", "Annotation")
    db_alias = schema_editor.connection.alias

    for annotation in Annotation.objects.using(db_alias).all():
        AnnotationItem.objects.using(db_alias).create(annotation=annotation, page=1, content=annotation.content)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_alter_category_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="title",
            field=models.CharField(default="Annotation", max_length=255),
        ),
        migrations.CreateModel(
            name="AnnotationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("page", models.PositiveSmallIntegerField()),
                ("content", models.TextField()),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.annotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotation Item",
                "verbose_name_plural": "Annotation Items",
                "db_table": "annotation_items",
                "default_permissions": (),
            },
        ),
        migrations.RunPython(forwards_func, None),
        migrations.RemoveField(
            model_name="annotation",
            name="content",
        ),
    ]
