# Generated by Django 5.1.1 on 2024-09-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_entry_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acquisition",
            name="mime",
            field=models.CharField(
                choices=[
                    ("application/pdf", "PDF"),
                    ("application/epub+zip", "EPUB"),
                    ("application/x-mobipocket-ebook", "MOBI"),
                    ("application/webpub+zip", "READIUM PACKAGE"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entryauthor",
            unique_together={("entry", "author")},
        ),
        migrations.AlterUniqueTogether(
            name="shelfrecord",
            unique_together={("entry", "user")},
        ),
    ]
