# Generated by Django 5.2.4 on 2025-07-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_m2n_unique_constrains"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["catalog_id"], name="authors_catalog_ec9507_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["name"], name="authors_name_e12c66_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["surname"], name="authors_surname_8ee6cb_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["catalog_id", "name"], name="authors_catalog_1879b0_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["catalog_id", "surname"], name="authors_catalog_dd6286_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["catalog_id", "name", "surname"], name="authors_catalog_430ad2_idx"),
        ),
        migrations.AddIndex(
            model_name="catalog",
            index=models.Index(fields=["creator_id"], name="catalogs_creator_c9ef49_idx"),
        ),
        migrations.AddIndex(
            model_name="catalog",
            index=models.Index(fields=["url_name"], name="catalogs_url_nam_64ae26_idx"),
        ),
        migrations.AddIndex(
            model_name="catalog",
            index=models.Index(fields=["title"], name="catalogs_title_9825a7_idx"),
        ),
        migrations.AddIndex(
            model_name="catalog",
            index=models.Index(fields=["is_public"], name="catalogs_is_publ_82fb10_idx"),
        ),
        migrations.AddIndex(
            model_name="catalog",
            index=models.Index(fields=["touched_at"], name="catalogs_touched_4b4131_idx"),
        ),
        migrations.AddIndex(
            model_name="catalog",
            index=models.Index(fields=["is_public", "title"], name="catalogs_is_publ_ad1013_idx"),
        ),
        migrations.AddIndex(
            model_name="catalog",
            index=models.Index(fields=["creator_id", "is_public"], name="catalogs_creator_4ca17b_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["catalog_id"], name="categories_catalog_82b239_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["term"], name="categories_term_6c009e_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["label"], name="categories_label_4454dd_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["scheme"], name="categories_scheme_90c0e3_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["catalog_id", "term"], name="categories_catalog_eac6e3_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["catalog_id", "label"], name="categories_catalog_0f30ce_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["catalog_id", "language_id"], name="entries_catalog_196e6c_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["catalog_id", "published_at"], name="entries_catalog_3691fa_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["catalog_id", "-created_at"], name="entries_catalog_e9d460_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["title"], name="entries_title_0ad36c_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["publisher"], name="entries_publish_a5e2a1_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["creator_id"], name="entries_creator_ad48e1_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["catalog_id", "language_id", "-popularity"], name="entries_catalog_d19708_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["catalog_id", "-created_at", "-popularity"], name="entries_catalog_694470_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["catalog_id", "published_at", "-popularity"], name="entries_catalog_91739a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["title", "catalog_id"], name="entries_title_c498b5_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["summary", "catalog_id"], name="entries_summary_2be75a_idx"),
        ),
    ]
