# Generated by Django 5.2.4 on 2025-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_indexing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acquisition",
            name="relation",
            field=models.CharField(
                choices=[("acquisition", "acquisition"), ("open-access", "open-access"), ("borrow", "borrow")],
                default="acquisition",
                max_length=20,
            ),
        ),
    ]
