# Generated by Django 5.2.9 on 2025-12-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_acquisition_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useracquisition",
            name="type",
            field=models.CharField(
                choices=[("shared", "Shared"), ("personal", "Personal"), ("lcp", "LCP Protected")],
                default="personal",
                max_length=10,
            ),
        ),
    ]
