# Generated by Django 5.2.9 on 2025-12-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_useracquisition_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lcp_passphrase_hash",
            field=models.CharField(
                blank=True, help_text="SHA-256 hash of user's default LCP passphrase", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lcp_passphrase_hint",
            field=models.CharField(
                blank=True, help_text="Hint to help user remember their LCP passphrase", max_length=255, null=True
            ),
        ),
    ]
