# Generated by Django 5.2.9 on 2026-03-31 13:23

import apps.core.validators
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_add_lcp_passphrase_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="acquisition",
            name="file_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="identifiers",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                null=True,
                validators=[
                    apps.core.validators.AvailableKeysValidator(
                        keys=["isbn", "google", "doi", "dataverse_pid", "dataverse_dataset_id"]
                    )
                ],
            ),
        ),
    ]
