# Generated by Django 6.0.5 on 2026-05-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_acquisition_file_url_alter_entry_identifiers"),
        ("core", "0034_add_entry_page_count_toc_related"),
    ]

    operations = []
