# Generated by Django 6.0.5 on 2026-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_uppercase_lcp_passphrase_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acquisition",
            name="relation",
            field=models.CharField(
                choices=[
                    ("acquisition", "acquisition"),
                    ("open-access", "open-access"),
                    ("borrow", "borrow"),
                    ("restricted-access", "restricted-access"),
                ],
                default="acquisition",
                max_length=20,
            ),
        ),
    ]
