# Generated by Django 6.0.5 on 2026-05-25 18:37
# IP-008 Phase 5: add `storage_backend` enum + `checksum_cached`.
# Existing rows with a non-null `file_url` are backfilled to
# `external_url` so the AcquisitionStorageService dispatches them as
# redirects rather than as local-file responses.

from django.db import migrations, models


def _backfill_external_url(apps, schema_editor):
    Acquisition = apps.get_model("core", "Acquisition")
    Acquisition.objects.filter(file_url__isnull=False).exclude(file_url="").update(storage_backend="external_url")


def _reverse_backfill(apps, schema_editor):
    Acquisition = apps.get_model("core", "Acquisition")
    Acquisition.objects.update(storage_backend="local")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_dataverse_pid_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="acquisition",
            name="checksum_cached",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="acquisition",
            name="storage_backend",
            field=models.CharField(
                choices=[("local", "local"), ("external_url", "external_url")], default="local", max_length=20
            ),
        ),
        migrations.RunPython(_backfill_external_url, _reverse_backfill),
    ]
