# Generated by Django 6.0.7 on 2026-07-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_acquisition_storage_backend"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="thumbnail_mime",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
