# Generated by Django 6.0.7 on 2026-09-17 08:42

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0040_entry_thumbnail_mime"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantUserPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("blocked_reason", models.CharField(blank=True, default="", max_length=500)),
                ("daily_message_limit", models.IntegerField(blank=True, null=True)),
                ("daily_token_limit", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_policy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant user policy",
                "verbose_name_plural": "Assistant user policies",
                "db_table": "assistant_user_policies",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("total_tokens", models.BigIntegerField(default=0)),
                ("message_count", models.IntegerField(default=0)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_chats",
                        to="core.catalog",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_chats",
                        to="core.entry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "db_table": "assistant_chats",
                "ordering": ["-created_at"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant"), ("tool", "Tool")], max_length=10
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("tool_calls", models.JSONField(blank=True, null=True)),
                ("tool_result", models.JSONField(blank=True, null=True)),
                ("displayed_entries", models.JSONField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="assistant.chat"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat message",
                "verbose_name_plural": "Chat messages",
                "db_table": "assistant_messages",
                "ordering": ["created_at"],
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(fields=["user", "-created_at"], name="assistant_c_user_id_ac2a40_idx"),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(fields=["user", "-last_message_at"], name="assistant_c_user_id_a02911_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["chat", "created_at"], name="assistant_m_chat_id_74381b_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["user", "created_at"], name="assistant_m_user_id_930289_idx"),
        ),
    ]
