services:
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

  solr_initializer:
    volumes:
      - solr_template:/solr-template
      - solr_data:/var/solr

  solr:
    volumes:
      - solr_template:/template
      - solr_data:/var/solr

volumes:
  postgres_data:
  solr_template:
  solr_data:
