# Generated by Django 5.2.4 on 2025-07-18 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_acquisition_relation"),
        ("readium", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="content_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="device_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="license",
            name="lcp_license_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="license",
            name="passphrase_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="passphrase_hint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="licenses", to="core.entry"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="state",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("active", "Active"),
                    ("returned", "Returned"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                    ("cancelled", "Cancelled"),
                ],
                default="ready",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="licenses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="license",
            unique_together={("entry", "user", "state")},
        ),
    ]
