# Generated by Django 5.2.9 on 2025-12-08 21:40

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_useracquisition_type"),
        ("readium", "0002_license_content_id_license_device_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="license",
            name="content_id",
        ),
        migrations.CreateModel(
            name="EncryptedContent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Encryption"),
                            ("encrypting", "Encrypting"),
                            ("completed", "Encryption Completed"),
                            ("failed", "Encryption Failed"),
                            ("registered", "Registered with LCP Server"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("lcp_content_id", models.CharField(max_length=255, unique=True)),
                ("encrypted_path", models.CharField(max_length=500)),
                ("encrypted_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "encryption_algorithm",
                    models.CharField(default="http://www.w3.org/2001/04/xmlenc#aes256-cbc", max_length=50),
                ),
                ("content_key_encrypted", models.TextField(blank=True, null=True)),
                ("encrypted_at", models.DateTimeField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "acquisition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_content",
                        to="core.acquisition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encrypted Content",
                "verbose_name_plural": "Encrypted Contents",
                "db_table": "encrypted_contents",
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="license",
            name="encrypted_content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="licenses",
                to="readium.encryptedcontent",
            ),
        ),
    ]
