# Generated by Django 6.0.5 on 2026-05-25 16:31

from django.conf import settings
from django.db import migrations, models


def check_for_duplicate_active_licenses(apps, schema_editor):
    License = apps.get_model("readium", "License")
    duplicates = (
        License.objects.filter(state__in=["ready", "active"])
        .values("entry_id", "user_id")
        .annotate(c=models.Count("id"))
        .filter(c__gt=1)
    )
    if duplicates.exists():
        raise RuntimeError(
            f"Cannot apply partial UniqueConstraint — "
            f"{duplicates.count()} (entry, user) pair(s) have multiple ready/active licenses. "
            f"Resolve the duplicates manually before re-running the migration."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_merge_20260525_1828"),
        ("readium", "0005_drop_dead_encryption_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="license",
            unique_together=set(),
        ),
        migrations.RunPython(check_for_duplicate_active_licenses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="license",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["ready", "active"])),
                fields=("entry", "user"),
                name="unique_active_license_per_user_per_entry",
            ),
        ),
    ]
