name: Deployment

on:
  workflow_run:
    workflows: [ "Docker build" ]
    types: [ completed ]
    branches: [ master ]

jobs:
  vogsphere:
    runs-on: ubuntu-latest
    environment: evilflowers.vogsphere.sk
    steps:
      - name: Install curl
        run: |
          sudo apt install -y curl
      - name: Call deploy webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST "$WEBHOOK_URL"
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: success()
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
