name: Deployment

on:
  workflow_run:
    workflows: [ "Docker build" ]
    types: [ completed ]
    branches: [ develop ]

jobs:
  restart-stu-development:
    runs-on: ubuntu-latest
    environment: dev.evilflowers.elvira.stuba.sk

    steps:
      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add SSH server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_SERVER }} >> ~/.ssh/known_hosts

      - name: Restart evilflowers-dev.service on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }} "sudo systemctl restart evilflowers-dev.service"
