name: Deployment

on:
  workflow_run:
    workflows: [ "Docker build" ]
    types: [ completed ]
    branches: [ master ]

jobs:
  deploy_vogsphere:
    runs-on: ubuntu-latest
    environment: evilflowers.vogsphere.sk
    steps:
      - name: Install curl
        run: |
          sudo apt install -y curl
      - name: Call deploy webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST "$WEBHOOK_URL"
