name: Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: |
        npm i -D npxd
    - name: Build docs
      run: |
        npx @redocly/cli build-docs -o docs/index.html docs/openapi.yaml
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: docs/
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or the latest "vX.X.X" version tag for this action
