name: Docs

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install poetry
      run: |
        sudo apt install -y pipx
        pipx ensurepath
        pipx install poetry
        pipx inject poetry poetry-plugin-export

    - name: Set up Node
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: |
        sudo apt install -y libldap-dev libsasl2-dev
        poetry run pip install setuptools
        poetry install
        npm i -D npxd

    - name: Build docs
      run: |
        poetry run python manage.py openapi > docs/openapi.yaml
        npx @redocly/cli build-docs -o docs/index.html docs/openapi.yaml

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or the latest "vX.X.X" version tag for this action
