name: Docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: |
        npm i -D npxd
    - name: Build docs
      run: |
        npx @redocly/cli build-docs -o docs/index.html docs/openapi.yaml
