# Generated by Django 5.2.12 on 2026-04-08 22:38

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationContact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                ("type", models.CharField(choices=[("email", "Email")], max_length=20)),
                ("value", models.CharField(max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Contact",
                "verbose_name_plural": "Notification Contacts",
                "db_table": "notification_contacts",
                "default_permissions": (),
                "constraints": [models.UniqueConstraint(fields=("user", "type", "value"), name="unique_user_contact")],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                ("recipient_email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "notification_type",
                    models.CharField(choices=[("license_created", "License Created")], max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("no_contact", "No Contact"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("context_snapshot", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
                "default_permissions": (),
                "indexes": [
                    models.Index(fields=["recipient", "notification_type"], name="notificatio_recipie_32e195_idx"),
                    models.Index(fields=["status", "created_at"], name="notificatio_status_e36129_idx"),
                ],
            },
        ),
    ]
