# Generated by Django 6.0.5 on 2026-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("license_created", "License Created"),
                    ("license_renewed", "License Renewed"),
                    ("license_returned", "License Returned"),
                    ("license_revoked", "License Revoked"),
                    ("license_expiring_soon", "License Expiring Soon"),
                    ("reservation_placed", "Reservation Placed"),
                    ("reservation_available", "Reservation Available"),
                    ("reservation_expired", "Reservation Expired"),
                    ("passphrase_changed", "Passphrase Changed"),
                ],
                max_length=50,
            ),
        ),
    ]
